3 + 2;      // Suma (5)
50 - 10;    // Resta (40)
10 * 20;    // Multiplicacion (200)
20 / 2      // Division (10)
'Jose' + 'Rios' // Concatenacion ('JoseRios')
3 == '3'    // Compara si los valores son iguales (true)
3 === '3'   // Compara si los valores y tipo de dato son iguales (false)
3 < 5       // Compara si el valor es menor (true)
3 > 3       // Compara si el valor es mayor (false)
3 <= 4      // Compara si el valor es menor o igual (true)
3 >= 4      // Compara si el valor es mayor o igual (false)

